
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/GramaphoneStore/frontend
      - node_modules:/GramaphoneStore/frontend/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: backend.Dockerfile
    env_file:
      - ./backend/.env

    ports:
      - "5555:5555"
    volumes:
      - ./backend:/GramaphoneStore/backend
    depends_on:
      - mongo
      


  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:
  node_modules:

     
